name: CD
on:
  workflow_dispatch:
jobs:
  publish:
    strategy:
      fail-fast: true
      matrix:
        registries:
          - url: https://registry.npmjs.org
            env: NPM_TOKEN
          - url: https://npm.pkg.github.com
            env: GITHUB_TOKEN
    env:
      NODE_ENV: test
      DEBUG: '*'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: ${{ matrix.registries.url }}
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Publish
        run: yarn publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets[matrix.registries.env] }}
